services:
  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - fullstack-network
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
    - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    - postgres-volume:/var/lib/postgresql/data

  pg-restore:
    image: postgres:14
    command: >
      bash -c "pg_restore -U postgres -d promoboa /docker-entrypoint-initdb.d/dump.sql"
    depends_on:
      - postgres

  node:
    container_name: node
    build: .
    image: fullstack/backend
    networks:
      - fullstack-network
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env


networks:
  fullstack-network:
    name: fullstack-network
    driver: bridge

volumes:
  postgres-volume: